function [Base_Band_Sig] = Transmitter(Data, Filter_Params)
    % Modulate the signal
    Modulated_Sig = Modulator(Data);
    %figure(); plot(abs(fft(modulated_sig)));
    % Upsample the modulated signal by 16
    Upsampled_Mod_Sig = Upsample(Modulated_Sig);
    %Initialize the Fir coefficients of the RRC Filter
    rf      = Filter_Params(1);
    span    = Filter_Params(2);
    sps     = Filter_Params(3);
    
    Impulse_Response = Filter(rf, span, sps);
    % Filter the Upsampled Data using the Impulse Response generated by
    % Rcosdesign
    Base_Band_Sig = conv(Upsampled_Mod_Sig,Impulse_Response,'same');
end

